[LOCAL]
members.file.path = data/raw/member_details.csv
loans.file.path = data/raw/loan_details.csv
loan_repayment.file.path = data/raw/loan_repayments.csv
loan_defaulters.file.path = data/raw/loan_defaulters.csv

members.output.clean.path = data/clean/members
loans.output.clean.path = data/clean/loans
loan_repayment.output.clean.path = data/clean/loan_repayment
loan_defaulters_delinq.output.clean.path = data/clean/loan_defaulters_delinq
loan_defaulters.output.clean.path = data/clean/loan_defaulters

members.output.processed.path = data/processed/members
loans.output.processed.path = data/processed/loans
loan_repayment.processed.clean.path = data/processed/loan_repayment
loan_defaulters_delinq.processed.clean.path = data/processed/loan_defaulters_delinq
loan_defaulters.output.processed.path = data/processed/loan_defaulters

members.output.bad.path = data/dq_reject/members
loans.output.bad.path = data/dq_reject/loans
loan_repayment.output.bad.path = data/dq_reject/loan_repayment
loan_defaulters.output.bad.path = data/dq_reject/loan_defaulters

final_data.output.path=data/curated/loan_grade_calculation

test.output.file.path = data/test
scd.staging.output.file.path=data/staging

[TEST]
members.file.path = data/raw/member_details.csv
loans.file.path = data/raw/loan_details.csv
loan_repayment.file.path = data/raw/loan_repayments.csv
loan_defaulters.file.path = data/raw/loan_defaulters.csv

members.output.clean.path = data/clean/members
loans.output.clean.path = data/clean/loans
loan_repayment.output.clean.path = data/clean/loan_repayment
loan_defaulters_delinq.output.clean.path = data/clean/loan_defaulters_delinq
loan_defaulters.output.clean.path = data/clean/loan_defaulters

members.output.processed.path = data/processed/members
loans.output.processed.path = data/processed/loans
loan_repayment.processed.clean.path = data/processed/loan_repayment
loan_defaulters_delinq.processed.clean.path = data/processed/loan_defaulters_delinq
loan_defaulters.output.processed.path = data/processed/loan_defaulters

members.output.bad.path = data/dq_reject/members
loans.output.bad.path = data/dq_reject/loans
loan_repayment.output.bad.path = data/dq_reject/loan_repayment
loan_defaulters_delinq.bad.path = data/dq_reject/loan_defaulters_delinq
loan_defaulters.output.bad.path = data/dq_reject/loan_defaulters

final_data.output.path=data/curated/loan_grade_calculation

test.output.file.path = data/test
scd.staging.output.file.path=data/staging

[PROD]
members.file.path = data/raw/member_details.csv
loans.file.path = data/raw/loan_details.csv
loan_repayment.file.path = data/raw/loan_repayments.csv
loan_defaulters.file.path = data/raw/loan_defaulters.csv

members.output.clean.path = data/clean/members
loans.output.clean.path = data/clean/loans
loan_repayment.output.clean.path = data/clean/loan_repayment
loan_defaulters_delinq.output.clean.path = data/clean/loan_defaulters_delinq
loan_defaulters.output.clean.path = data/clean/loan_defaulters

members.output.processed.path = data/processed/members
loans.output.processed.path = data/processed/loans
loan_repayment.processed.clean.path = data/processed/loan_repayment
loan_defaulters_delinq.processed.clean.path = data/processed/loan_defaulters_delinq
loan_defaulters.output.processed.path = data/processed/loan_defaulters

members.output.bad.path = data/dq_reject/members
loans.output.bad.path = data/dq_reject/loans
loan_repayment.output.bad.path = data/dq_reject/loan_repayment
loan_defaulters_delinq.bad.path = data/dq_reject/loan_defaulters_delinq
loan_defaulters.output.bad.path = data/dq_reject/loan_defaulters

final_data.output.path=data/curated/loan_grade_calculation

test.output.file.path = data/test
scd.staging.output.file.path=data/staging