[LOCAL]
members.file.path = data/member_details.csv
loans.file.path = data/loan_details.csv
loan_repayment.file.path = data/loan_repayments.csv
loan_defaulters.file.path = data/loan_defaulters.csv
[TEST]
members.file.path = data/member_details.csv
loans.file.path = data/loan_details.csv
loan_repayment.file.path = data/loan_repayments.csv
loan_defaulters.file.path = data/loan_defaulters.csv
[PROD]
members.file.path = data/member_details.csv
loans.file.path = data/loan_details.csv
loan_repayment.file.path = data/loan_repayments.csv
loan_defaulters.file.path = data/loan_defaulters.csv