[LOCAL]
members.file.path = data/raw/member_details.csv
loans.file.path = data/raw/loan_details.csv
loan_repayment.file.path = data/raw/loan_repayments.csv
loan_defaulters.file.path = data/raw/loan_defaulters.csv

members.output.path = data/processed/members
loans.output.path = data/processed/loans
loan_repayment.output.path = data/processed/loan_repayment
loan_defaulters.output.path = data/processed/loan_defaulters

[TEST]
members.file.path = data/raw/member_details.csv
loans.file.path = data/raw/loan_details.csv
loan_repayment.file.path = data/raw/loan_repayments.csv
loan_defaulters.file.path = data/raw/loan_defaulters.csv

members.output.path = data/processed/members
loans.output.path = data/processed/loans
loan_repayment.output.path = data/processed/loan_repayment
loan_defaulters.output.path = data/processed/loan_defaulters

[PROD]
members.file.path = data/raw/member_details.csv
loans.file.path = data/raw/loan_details.csv
loan_repayment.file.path = data/raw/loan_repayments.csv
loan_defaulters.file.path = data/raw/loan_defaulters.csv

members.output.path = data/processed/members
loans.output.path = data/processed/loans
loan_repayment.output.path = data/processed/loan_repayment
loan_defaulters.output.path = data/processed/loan_defaulters