status = error
name = PropertiesConfig

filters = threshold
filter.threshold.type = ThresholdFilter
filter.threshold.level = debug

#display and write
appenders = console,file 
#Appenders to print logs while pipelines are running
appender.console.type = Console
appender.console.name = Console
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %-5p %c{1}: %m%n

#Appenders to write logs to a destination
appender.file.type = File
appender.file.name = FileAppender
appender.file.fileName = logs/pipeline.log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d{yy/MM/dd HH:mm:ss} %-5p %c{1}: %m%n

loggers = spark, spark_repl, parquet, hadoop, app

logger.spark.name = org.apache.spark
logger.spark.level = warn
logger.spark.additivity = false
logger.spark.appenderRefs = console
logger.spark.appenderRef.console.ref = Console

logger.spark_repl.name = org.apache.spark.repl
logger.spark_repl.level = info
logger.spark_repl.additivity = false
logger.spark_repl.appenderRefs = console
logger.spark_repl.appenderRef.console.ref = Console

logger.parquet.name = org.apache.parquet
logger.parquet.level = error
logger.parquet.additivity = false
logger.parquet.appenderRefs = console
logger.parquet.appenderRef.console.ref = Console

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = error
logger.hadoop.additivity = false
logger.hadoop.appenderRefs = console
logger.hadoop.appenderRef.console.ref = Console

# Mapping app logger to both Console and FileAppender
logger.app.name = lending_club_app
logger.app.level = info
logger.app.additivity = false
logger.app.appenderRefs = console,file
logger.app.appenderRef.console.ref = Console
logger.app.appenderRef.file.ref = FileAppender

#Mapping the global root logger to both Console and FileAppender
rootLogger.level = info
rootLogger.appenderRefs = console,file
rootLogger.appenderRef.console.ref = Console
logger.app.appenderRef.file.ref = FileAppender