[LOCAL]
spark.app.name = lending_club_project
[TEST]
spark.app.name = lending_club_project_test
spark.executor.instances = 3
spark.executor.cores = 5
spark.executor.memory = 15GB
[PROD]
spark.app.name = lending_club_project_prod
spark.executor.instances = 3
spark.executor.cores = 5
spark.executor.memory = 15GB